#!/usr/bin/expect
set ipadd [lindex $argv 0]
set port [lindex $argv 1]
set username [lindex $argv 2]
set userpasswd [lindex $argv 3]
set rootpasswd [lindex $argv 4]
set timeout 10
spawn ssh $username@$ipadd -p $port
expect {
  "password" {send "$userpasswd\r";exp_continue}
  "*from*" {send "su - root\r";exp_continue}
  "*assword*" {send "$rootpasswd\r";exp_continue}
  "*]#" {send "rm -rf /tmp/*${ipadd}* /tmp/inuxcheck.sh /tmp/dangerstcpports.dat /tmp/dangersudports.dat\r"}
}
expect eof

